掲示板一覧ページの作成
hidemaru11/tenkue-board-r001 pull request #5
Opened 2020-09-01 04:56 UTC by hidemaru11

掲示板一覧ページを作成しました。
コメント、いいね部分はダミーとして"#"を入れてあります。

懸念点：
- n+1問題について調べた内容に沿って実装しましたが、内容の理解は不十分かと思います。
- 掲示板詳細にとんだ際、未ログインユーザーだとエラーが起きていたので修正しましたが、本来であれば詳細ページを担当されている松岡さんに修正依頼をすべきだったかもしれません。

ご確認よろしくお願い致します。

2020-09-01 05:23 UTC, yamken314 commented on app/controllers/posts_controller.rb
>    end
`.order(created_at: :desc)を`
postsモデルにスコープを定義して呼び出してもいいかなと思いました。

models/post.rb
`scope :sorted_desc, -> { order(created_at: :desc) }`

`@posts = Post.all.includes(:user).sorted_desc`
見た目がすっきりするのと、使い回しが出来て便利です。

2020-09-01 07:42 UTC, hidemaru11 commented on app/controllers/posts_controller.rb
>    end
ヒントを頂きありがとうございます！追加しました！

2020-09-01 12:06 UTC, sew-sou19 requested changes
レビュー完了しました！修正完了したら再度レビュー依頼してください！

2020-09-01 12:06 UTC, masato-sa93 commented on app/views/posts/index.html.erb
> +                    <span>投稿日時：<%= post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
`strftime("%Y-%m-%d %H:%M")`はshow.html.erbにも同じ表記があるので、こういう場合はヘルパーメソッドを定義するのが良いです！

2020-09-01 12:06 UTC, masato-sa93 commented on app/views/posts/index.html.erb
> +                  <% if current_user && current_user.id == post.user.id %>
「ユーザーがログイン状態か」を条件分岐させる場合は、`if user_signed_in?`の方がいいかと思います！
https://qiita.com/tobita0000/items/866de191635e6d74e392

2020-09-01 12:06 UTC, masato-sa93 commented on app/views/posts/show.html.erb
> +            <% if current_user && current_user.id == @post.user.id %>
ここも同じ指摘です！（`user_signed_in?`）

2020-09-01 12:06 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
>    end
スコープは素晴らしいですね！
もう一つ突っ込むなら、`includes(:user)`もスコープで定義できます😇

2020-09-01 18:45 UTC, hidemaru11 commented on app/controllers/posts_controller.rb
>    end
メソッド名を迷いましたが、`includes(:user)`もスコープ定義しました。

2020-09-01 19:38 UTC, hidemaru11 commented on app/views/posts/index.html.erb
> +                    <span>投稿日時：<%= post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
ヘルパーメソッドを追加し、viewに反映しました！

2020-09-01 19:54 UTC, hidemaru11 commented on app/views/posts/index.html.erb
> +                  <% if current_user && current_user.id == post.user.id %>
ご指摘の通り修正してみましたが、これだと他の投稿者の投稿まで編集・削除ができるようになってしまうようです。
ここでの条件分岐は「ユーザーがログイン状態か」ではなく「ログインしているユーザーが投稿したユーザーか」という認識であっていますでしょうか？

2020-09-01 19:56 UTC, hidemaru11 commented on app/views/posts/show.html.erb
> +            <% if current_user && current_user.id == @post.user.id %>
上記と同様の状況かと思いますがいかがでしょうか？

2020-09-02 01:33 UTC, hidemaru11 commented on app/views/posts/index.html.erb
> +                  <% if current_user && current_user.id == post.user.id %>
ご指摘の意味を取り違えておりました、失礼しました！
修正致しました！

2020-09-02 01:33 UTC, hidemaru11 commented on app/views/posts/show.html.erb
> +            <% if current_user && current_user.id == @post.user.id %>
上記と同じく、修正しました！

2020-09-02 01:48 UTC, sew-sou19 approved these changes
LGTM！お疲れ様でした！

2020-09-02 01:48 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
>    end
OKです！スコープ名はチームで決めるor意味が明確なものなら大丈夫だと思います！

2020-09-02 01:59 UTC, merged