いいね機能の実装
hidemaru11/tenkue-board-r001 pull request #6
Opened 2020-09-01 12:30 UTC by takanori19910907

遅くなってしまい申し訳ございません！
いいね機能の実装が完了したため確認をお願い致します！
☑︎1ユーザーあたり1回のみ処理
☑︎いいね/いいね済みの表示切り替え
☑︎未ログイン時は実行出来ないよう規制
☑︎いいねのカウント処理
全て完了しております。

pullしたタイミングが投稿詳細画面の実装直後だったため、posts/showにて実装しています。
ログアウト処理が出来ず、複数ユーザーのいる画面で確認がとれていないため、もしかしたら不具合が生じているかもしれません...もしなにかありましたらMTGのときにご教授いただけると幸いです！

2020-09-03 03:16 UTC, sew-sou19 requested changes
コードレビュー完了しました。修正して再度依頼してください！

2020-09-03 03:16 UTC, masato-sa93 commented on Gemfile.lock
> +    autoprefixer-rails (9.8.6.3)
これ`bundle update`されてませんか？
今回は修正不要ですが、本番環境でbundle updateをすると不具合の原因になります。
必要がない限り安易にbundle updateしないようにしましょう！

2020-09-03 03:16 UTC, masato-sa93 commented on app/controllers/likes_controller.rb
> +    unless @post.id == current_user.id
このunless文は何を意図されていますでしょうか？
postのidとユーザーのidが一致しない場合にのみ、いいねができるようにすると読み取れるのですが、、、

2020-09-03 03:16 UTC, masato-sa93 commented on app/controllers/likes_controller.rb
> +    def set_like
メソッド名と内容がバラバラなので、メソッド名を修正しましょう。

2020-09-03 03:16 UTC, masato-sa93 commented on app/controllers/likes_controller.rb
> +      post = Post.find(params[:post_id])
before actionで@postインスタンスを定義してますが、ここでpostを追加で定義する理由はなんでしょうか？

2020-09-03 03:16 UTC, sew-sou19 commented on app/models/post.rb
> +  has_many :liked_users, through: :likes, source: :user
これって何のためのアソシエーションですか？？
別名定義は確かに使えますが、ビューでもコントローラーでも使っている気配がないので、不要かと思いますが、、、

2020-09-03 03:16 UTC, sew-sou19 commented on app/models/user.rb
> +  has_many :like_posts, through: :likes, source: :post
これも何のためのアソシエーションでしょうか？

2020-09-03 03:16 UTC, sew-sou19 commented on app/models/post.rb
> +  has_many :likes
投稿(post)が削除された時に、関連するlikesも削除されるように定義しましょう。

2020-09-03 03:16 UTC, sew-sou19 commented on app/models/post.rb
> +    likes.where(user_id: user.id).exists?
アソシエーションがあるので、わざわざwhere句を使う必要ないです。
`self~~`で行けると思います

2020-09-03 03:16 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
この記述だと、未ログイン時にエラー出ないですか？
出なければ問題ありません。

2020-09-03 03:16 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +  <%= link_to(post_likes_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
jsは完了定義に入れてないのでコードレビューはしませんが、気になったので一つだけ。
`id: :"like-button-#{post.id}")`の、id名の前の:は不要かと

2020-09-03 03:16 UTC, sew-sou19 commented on app/views/posts/show.html.erb
> +            <span>投稿日時 : <%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
ここはヘルパーメソッドを使った記述に戻しましょう

2020-09-03 03:16 UTC, sew-sou19 commented on app/views/posts/show.html.erb
> +            <% if current_user.id == @post.user.id %>
ここも前の記述に戻しましょう

2020-09-03 03:16 UTC, sew-sou19 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
`resource`は、対象データが一つだけの場合に使う定義方法です。
これだとdeleteの時に不具合が発生するはずなので、resourcesを使用してください。

2020-09-03 03:16 UTC, sew-sou19 commented on config/routes.rb
> +    # post 'add' => 'likes#create'
不要な記述は削除しましょう。もし残したいならコメントでなぜ残すのかを注釈入れましょう。

2020-09-03 16:30 UTC, takanori19910907 commented on Gemfile.lock
> +    autoprefixer-rails (9.8.6.3)
先ほど調べて初めてコマンドの意味を理解しました...意図しないgemのバージョンにも関与してしまうものなのですね...
今後ないようにします！

2020-09-03 16:32 UTC, takanori19910907 commented on app/controllers/likes_controller.rb
> +    unless @post.id == current_user.id
こちらは自分自身の投稿に対していいねすることを制限する目的で実装しました。
ただ、実際のSNSはその規制も特にしていないですね...自分の思い込みで書いたものなので削除しました！

2020-09-03 16:41 UTC, takanori19910907 commented on app/controllers/likes_controller.rb
> +    def set_like
修正しました！以後メソッド名もわかりやすく書くよう意識します！

2020-09-03 16:48 UTC, takanori19910907 commented on app/controllers/likes_controller.rb
> +      post = Post.find(params[:post_id])
before actionの意味を理解出来ておらず、各アクションで取得してしまっていました！
削除し、before actionで定義した@postからデータ取得するコードに修正しました。

2020-09-03 17:17 UTC, takanori19910907 commented on app/models/post.rb
> +  has_many :liked_users, through: :likes, source: :user
中間テーブルを挟んだアソシエーションはこのような書き方がmustなのかなと思っていましたが、誤った認識で学んでいました...has_many/belongs_toのみの書き方に修正しております。has_many throuth = 中間テーブルの中でも場合分け(フォローしている/していない等)で処理や表示が必要なケースに定義するもの、という認識で合っていますでしょうか?

2020-09-03 17:21 UTC, takanori19910907 commented on app/views/likes/_like.html.erb
> +  <%= link_to(post_likes_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
承知致しました、修正しました！

2020-09-03 17:38 UTC, takanori19910907 commented on app/views/posts/show.html.erb
> +            <span>投稿日時 : <%= @post.created_at.strftime("%Y-%m-%d %H:%M") %></span>
確認不足です...申し訳ございません！修正しました！

2020-09-03 17:38 UTC, takanori19910907 commented on app/views/posts/show.html.erb
> +            <% if current_user.id == @post.user.id %>
こちらも同様のミスです、申し訳ございません。

2020-09-03 17:40 UTC, takanori19910907 commented on config/routes.rb
> +    # post 'add' => 'likes#create'
承知致しました。今回消し忘れのため削除しました。以後消し忘れないように確認します！

2020-09-04 00:02 UTC, takanori19910907 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
resoucesでのルーティング実装を変更しました！
ただ、ネストしたDELETEリクエストのパスに含まれる[:id]について１点懸念があります。
link_to post_like_path(post,post.likes.ids)
上記のようなpost_idとpostが持っているlike.idをpathのidとして渡しているのですが、2つ目の引数で何を送るべきかがいまいちわかっていません。このような書き方であっておりますでしょうか?

2020-09-04 02:48 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    unless @post.id == current_user.id
OKです！

> 自分自身の投稿に対していいねすることを制限する

これをしたい場合は、下記にしないとですね。
```
@post.user_id == current_user.id
```

2020-09-04 02:55 UTC, sew-sou19 commented on app/models/post.rb
> +  has_many :liked_users, through: :likes, source: :user
ちょっと文字化けがあって質問の意図が正確に汲み取れませんが、下記あたりが参考になるかと思います

https://railsguides.jp/association_basics.html#has-many-through%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91

2020-09-04 03:07 UTC, masato-sa93 commented on app/views/likes/_like.html.erb
> +  <%= link_to(post_like_path(post,post.likes.ids), method: :delete, remote: true, id: "like-button-#{post.id}") do %>
link_toの引数に入ってる`post.likes.ids`は複数形だとまずい気がしますが、エラー起きてないでしょうか？（例えば複数人がいいねしてる状態で、そのうちの1人がいいねを取り消そうとしたとき）

2020-09-04 03:07 UTC, sew-sou19 commented on app/views/layouts/application.html.erb
> -      <%= render 'layouts/footer' %>
フッター消してしまって問題ないですか？

2020-09-04 03:07 UTC, sew-sou19 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
別途コメントしてますが、おそらくエラーが出るかと思います。`post.likes.ids`は、投稿(post)に紐づく複数のlikeを引っ張ってきているので。

2020-09-04 03:08 UTC, sew-sou19 commented on app/models/post.rb
> +    likes.where(user_id: user.id).exists?
これの解消もお願いしますー！

2020-09-04 03:10 UTC, sew-sou19 requested changes
レビューしましたー！
まだ一部修正点があるので、頑張って解消しましょう！

2020-09-04 03:10 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +<% if user_signed_in? &&　post.liked_by?(current_user) %>
これ全角スペース入ってませんか？
全角スペースはコンパイル時にエラーになりやすいので避けましょう

2020-09-04 08:10 UTC, sew-sou19 commented
コンフリクト解消しましょう！

2020-09-04 08:19 UTC, takanori19910907 commented
またもや確認不足ですみません...コンフリクトについて修正致しました！

2020-09-04 08:34 UTC, sew-sou19 requested changes
あと2点解消をお願いしますー！
自分で解消が難しければチーム内で話し合ってみてください。
個別のコードのレビューに対してリプor反応していただけると、僕の指摘が届いているのかわかるので助かります🙇‍♂️

2020-09-04 08:34 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
ここ変更された理由ってなんでしょうか？
これだと未ログイン時にエラー出るかと思います。

2020-09-04 08:34 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +  <%= link_to(post_like_path(post,post.likes.ids), method: :delete, remote: true, id: "like-button-#{post.id}") do %>
ここ要修正です。
取り消されるいいねがそのユーザーのいいねになってますでしょうか？

2020-09-04 11:47 UTC, yamken314 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
<% if post.liked_by?(current_user) %>
でエラーが出る原因は、未ログインなので、idが無い。なのでcurrent_userの引数にidが行かないのが原因だと思います。
<% if user_signed_in? &&　post.liked_by?(current_user) %>
でエラーが出ないのは、

2020-09-04 11:54 UTC, yamken314 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
<% if post.liked_by?(current_user) %>
でエラーが出る原因は、未ログインなので、idが無い。なのでcurrent_userの引数にidが行かないのが原因だと思います。

<% if user_signed_in? &&　post.liked_by?(current_user) %>
で未ログイン時エラーが出ないのは、if user_signed_in?でfalseになりその後のpost.liked_by?(current_user)
まで、処理が行かない為だと思います。

多分。。

2020-09-04 12:18 UTC, yamken314 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
> 未ログイン時にはいいねボタンを押せないようになっている

未ログインの人がいいねボタン押すと、ログイン画面へ遷移して「アカウント登録もしくはログインしてください。」のフラッシュが表示される仕組みですよね？

押しても、処理が走らないのは、要件が違う気がしますね。

2020-09-04 12:32 UTC, yamken314 commented on app/views/likes/_like.html.erb
> +<% if post.liked_by?(current_user) %>
未ログインの人の制限方法は、postsコントローラーのbefore_actionを参考にしてみて下さい。

また分からなければ聞いてください！

2020-09-04 13:53 UTC, yamken314 commented on config/routes.rb
> +    resource :likes, only: [:create, :destroy]
idsですが、調べると主キーを全て取得するらしいです。

> post.likes.idsは、投稿(post)に紐づく複数のlikeを引っ張ってきているので。

壮さんが言う様にpostに紐づくlikeの主キー全てを取得して送っている。

でもコントローラーではこうなってるんですよね？

```
 def destroy
   current_user.likes.find_by(post_id: @post.id).delete
 end
```

エラーが起きないのは不思議ですが、原因を探る為にbinding.pryで中身を確認するのもありですね。

調べたのですが
https://qiita.com/nojinoji/items/2c66499848d882c31ffa#postsshowhtmlerb-1
これは、どうなんでしょう？  

`link_to post_like_path(post)にして`
```
like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
like.destroy
```

2020-09-05 23:42 UTC, takanori19910907 commented
テンプレートエラーが発生し一度削除していたのですが、ご指摘の通りエラーとなってしまっていましたので、user user_signed_in? を再度追加しました！
またサンプルでは未ログイン時flashメッセージも表示していたため、ログイン判定のメソッドを追加しております。

2020-09-06 04:06 UTC, sew-sou19 requested changes
あと細かいですが、1点だけ（likes_controllerの記述）修正お願いしますー！

2020-09-06 04:06 UTC, masato-sa93 commented on app/controllers/likes_controller.rb
> +    current_user.likes.find_by(post_id: @post.id,id: params[:id]).delete
ここ記述が冗長になってます！
下記のいずれかで行けるかと思います。

```suggestion
    current_user.likes.find_by(post_id: @post.id)
```
こっちは、current_user.likesで、likeのuser_idは指定できているので、post_idで一つに絞り込んであげてるイメージ

```suggestion
    like = Like.find_by(id: params[:id])
    like.destroy
```
こっちは、単にlikeの主キーで絞り込んでるイメージ

2020-09-06 04:06 UTC, sew-sou19 commented on app/views/likes/_like.html.erb
> +  <%= link_to(post_like_path(post,Like.find_by(user_id:current_user.id,post_id: post.id)), method: :delete, remote: true, id: "like-button-#{post.id}") do %>
概ねOKです！
プレフィックスの引数にインスタンスの定義を入れると可読性が落ちるので、僕だったら下記の書き方にします。

```suggestion
  <% like = Like.find_by(user_id: current_user.id, post_id: @post.id) %>
  <%= link_to post_like_path(@post.id, like.id), method: :delete, class: "post_action_btn post_liked" do %>
```

2020-09-06 04:59 UTC, sew-sou19 approved these changes
一応動作はすると思うのでLGTMとします。（これ以上修正せずマージしていただいて大丈夫です）
指摘したポイントは理解していただくといいかと思いますー！

2020-09-06 05:00 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    current_user.likes.find_by(id:params[:id]).delete
意味合いが違います、、、
1行にするなら下記のいずれかです

```suggestion
    current_user.likes.find_by(post_id: @post.id).destroy
```

```suggestion
    Like.find_by(id: params[:id]).destroy
```

あとdeleteよりdestroyを使う方が無難です。
違いはググってみてください。

2020-09-06 05:20 UTC, takanori19910907 commented
承知致しました！ご指摘ありがとうございました！

2020-09-06 05:20 UTC, merged